// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        in1_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID,
        in1_V_TDATA,
        in1_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   in1_V_TVALID;
input   out0_V_TREADY;
input  [47:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [31:0] out0_V_TDATA;
output   out0_V_TVALID;
input  [31:0] in1_V_TDATA;
output   in1_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out0_V_TVALID;
reg in1_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] icmp_ln249_fu_276_p2;
wire   [0:0] icmp_ln253_fu_292_p2;
reg    ap_predicate_op40_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln249_reg_1193;
reg   [0:0] icmp_ln249_reg_1193_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_1303;
reg   [0:0] icmp_ln290_reg_1303_pp0_iter2_reg;
reg    ap_predicate_op239_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
reg    in1_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_1193_pp0_iter1_reg;
wire   [1:0] trunc_ln242_fu_288_p1;
wire   [47:0] tmp_fu_310_p11;
wire   [0:0] icmp_ln272_fu_354_p2;
reg   [0:0] icmp_ln272_reg_1218;
reg   [0:0] icmp_ln272_reg_1218_pp0_iter1_reg;
wire   [1:0] local_temp_fu_360_p1;
reg  signed [1:0] local_temp_reg_1223;
reg  signed [1:0] local_temp_1_reg_1228;
reg  signed [1:0] local_temp_2_reg_1233;
reg  signed [1:0] local_temp_3_reg_1238;
reg  signed [1:0] local_temp_4_reg_1243;
reg  signed [1:0] local_temp_5_reg_1248;
reg  signed [1:0] local_temp_6_reg_1253;
reg  signed [1:0] local_temp_7_reg_1258;
reg  signed [1:0] local_temp_8_reg_1263;
reg  signed [1:0] local_temp_9_reg_1268;
reg  signed [1:0] local_temp_10_reg_1273;
reg  signed [1:0] local_temp_11_reg_1278;
reg  signed [1:0] local_temp_12_reg_1283;
reg  signed [1:0] local_temp_13_reg_1288;
reg  signed [1:0] local_temp_14_reg_1293;
reg  signed [1:0] local_temp_15_reg_1298;
wire   [0:0] icmp_ln290_fu_520_p2;
reg   [0:0] icmp_ln290_reg_1303_pp0_iter1_reg;
wire  signed [4:0] mul_ln115_13_fu_928_p2;
reg  signed [4:0] mul_ln115_13_reg_1307;
wire   [5:0] add_ln169_1_fu_988_p2;
reg   [5:0] add_ln169_1_reg_1312;
wire   [6:0] add_ln169_5_fu_1014_p2;
reg   [6:0] add_ln169_5_reg_1317;
wire   [6:0] add_ln169_9_fu_1040_p2;
reg   [6:0] add_ln169_9_reg_1322;
wire   [5:0] add_ln169_10_fu_1046_p2;
reg   [5:0] add_ln169_10_reg_1327;
wire   [6:0] add_ln169_12_fu_1062_p2;
reg   [6:0] add_ln169_12_reg_1332;
wire   [31:0] outElem_fu_1130_p2;
reg   [31:0] outElem_reg_1337;
wire   [47:0] ap_phi_reg_pp0_iter0_inElem_reg_237;
reg   [47:0] ap_phi_reg_pp0_iter1_inElem_reg_237;
reg   [31:0] sf_fu_186;
wire   [31:0] sf_2_fu_514_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [7:0] i_fu_190;
wire   [7:0] i_2_fu_282_p2;
reg   [7:0] ap_sig_allocacmp_i_1;
reg   [31:0] empty_fu_194;
reg   [47:0] inputBuf_fu_198;
reg   [47:0] inputBuf_1_fu_202;
reg   [47:0] inputBuf_2_fu_206;
reg   [47:0] inputBuf_3_fu_210;
reg   [31:0] nf_fu_214;
wire   [31:0] nf_5_fu_543_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [47:0] tmp_fu_310_p9;
wire   [1:0] tmp_fu_310_p10;
wire   [31:0] nf_4_fu_531_p2;
wire   [0:0] icmp_ln302_fu_537_p2;
wire   [2:0] r_fu_566_p1;
wire   [2:0] mul_ln115_fu_577_p0;
wire  signed [4:0] mul_ln115_fu_577_p2;
wire   [2:0] r_1_fu_587_p4;
wire   [2:0] mul_ln115_1_fu_604_p0;
wire  signed [4:0] mul_ln115_1_fu_604_p2;
wire   [2:0] r_2_fu_614_p4;
wire   [2:0] mul_ln115_2_fu_631_p0;
wire  signed [4:0] mul_ln115_2_fu_631_p2;
wire   [2:0] r_3_fu_641_p4;
wire   [2:0] mul_ln115_3_fu_658_p0;
wire  signed [4:0] mul_ln115_3_fu_658_p2;
wire   [2:0] r_4_fu_668_p4;
wire   [2:0] mul_ln115_4_fu_685_p0;
wire  signed [4:0] mul_ln115_4_fu_685_p2;
wire   [2:0] r_5_fu_695_p4;
wire   [2:0] mul_ln115_5_fu_712_p0;
wire  signed [4:0] mul_ln115_5_fu_712_p2;
wire   [2:0] r_6_fu_722_p4;
wire   [2:0] mul_ln115_6_fu_739_p0;
wire  signed [4:0] mul_ln115_6_fu_739_p2;
wire   [2:0] r_7_fu_749_p4;
wire   [2:0] mul_ln115_7_fu_766_p0;
wire  signed [4:0] mul_ln115_7_fu_766_p2;
wire   [2:0] r_8_fu_776_p4;
wire   [2:0] mul_ln115_8_fu_793_p0;
wire  signed [4:0] mul_ln115_8_fu_793_p2;
wire   [2:0] r_9_fu_803_p4;
wire   [2:0] mul_ln115_9_fu_820_p0;
wire  signed [4:0] mul_ln115_9_fu_820_p2;
wire   [2:0] r_10_fu_830_p4;
wire   [2:0] mul_ln115_10_fu_847_p0;
wire  signed [4:0] mul_ln115_10_fu_847_p2;
wire   [2:0] r_11_fu_857_p4;
wire   [2:0] mul_ln115_11_fu_874_p0;
wire  signed [4:0] mul_ln115_11_fu_874_p2;
wire   [2:0] r_12_fu_884_p4;
wire   [2:0] mul_ln115_12_fu_901_p0;
wire  signed [4:0] mul_ln115_12_fu_901_p2;
wire   [2:0] r_13_fu_911_p4;
wire   [2:0] mul_ln115_13_fu_928_p0;
wire   [2:0] r_14_fu_934_p4;
wire   [2:0] mul_ln115_14_fu_951_p0;
wire  signed [4:0] mul_ln115_14_fu_951_p2;
wire   [2:0] r_15_fu_961_p4;
wire   [2:0] mul_ln115_15_fu_978_p0;
wire  signed [4:0] mul_ln115_15_fu_978_p2;
wire  signed [5:0] sext_ln257_13_fu_957_p1;
wire  signed [5:0] sext_ln257_12_fu_907_p1;
wire  signed [5:0] sext_ln257_11_fu_880_p1;
wire  signed [5:0] sext_ln257_8_fu_799_p1;
wire   [5:0] add_ln169_3_fu_994_p2;
wire  signed [5:0] sext_ln257_7_fu_772_p1;
wire  signed [5:0] sext_ln257_10_fu_853_p1;
wire   [5:0] add_ln169_4_fu_1004_p2;
wire  signed [6:0] sext_ln169_4_fu_1010_p1;
wire  signed [6:0] sext_ln169_3_fu_1000_p1;
wire  signed [5:0] sext_ln257_9_fu_826_p1;
wire  signed [5:0] sext_ln257_fu_583_p1;
wire   [5:0] add_ln169_7_fu_1020_p2;
wire  signed [5:0] sext_ln257_2_fu_637_p1;
wire  signed [5:0] sext_ln257_1_fu_610_p1;
wire   [5:0] add_ln169_8_fu_1030_p2;
wire  signed [6:0] sext_ln169_7_fu_1036_p1;
wire  signed [6:0] sext_ln169_6_fu_1026_p1;
wire  signed [5:0] sext_ln257_4_fu_691_p1;
wire  signed [5:0] sext_ln257_3_fu_664_p1;
wire  signed [5:0] sext_ln257_5_fu_718_p1;
wire  signed [5:0] sext_ln169_1_fu_984_p1;
wire   [5:0] add_ln169_11_fu_1052_p2;
wire  signed [6:0] sext_ln169_10_fu_1058_p1;
wire  signed [6:0] sext_ln257_6_fu_745_p1;
wire   [31:0] select_ln272_fu_1071_p3;
wire  signed [31:0] sext_ln169_fu_1078_p1;
wire  signed [31:0] sext_ln169_2_fu_1087_p1;
wire   [31:0] add_ln169_fu_1081_p2;
wire  signed [31:0] sext_ln169_5_fu_1096_p1;
wire   [31:0] add_ln169_2_fu_1090_p2;
wire  signed [7:0] sext_ln169_11_fu_1111_p1;
wire  signed [7:0] sext_ln169_9_fu_1108_p1;
wire   [7:0] add_ln169_13_fu_1114_p2;
wire  signed [7:0] sext_ln169_8_fu_1105_p1;
wire   [7:0] add_ln169_14_fu_1120_p2;
wire  signed [31:0] sext_ln169_12_fu_1126_p1;
wire   [31:0] add_ln169_6_fu_1099_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_start_int;
wire   [4:0] mul_ln115_10_fu_847_p00;
wire   [4:0] mul_ln115_11_fu_874_p00;
wire   [4:0] mul_ln115_12_fu_901_p00;
wire   [4:0] mul_ln115_13_fu_928_p00;
wire   [4:0] mul_ln115_14_fu_951_p00;
wire   [4:0] mul_ln115_15_fu_978_p00;
wire   [4:0] mul_ln115_1_fu_604_p00;
wire   [4:0] mul_ln115_2_fu_631_p00;
wire   [4:0] mul_ln115_3_fu_658_p00;
wire   [4:0] mul_ln115_4_fu_685_p00;
wire   [4:0] mul_ln115_5_fu_712_p00;
wire   [4:0] mul_ln115_6_fu_739_p00;
wire   [4:0] mul_ln115_7_fu_766_p00;
wire   [4:0] mul_ln115_8_fu_793_p00;
wire   [4:0] mul_ln115_9_fu_820_p00;
wire   [4:0] mul_ln115_fu_577_p00;
reg    ap_condition_105;
wire   [1:0] tmp_fu_310_p1;
wire   [1:0] tmp_fu_310_p3;
wire  signed [1:0] tmp_fu_310_p5;
wire  signed [1:0] tmp_fu_310_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 sf_fu_186 = 32'd0;
#0 i_fu_190 = 8'd0;
#0 empty_fu_194 = 32'd0;
#0 inputBuf_fu_198 = 48'd0;
#0 inputBuf_1_fu_202 = 48'd0;
#0 inputBuf_2_fu_206 = 48'd0;
#0 inputBuf_3_fu_210 = 48'd0;
#0 nf_fu_214 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_4_sparsemux_9_2_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 48 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 48 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 48 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 48 ),
    .def_WIDTH( 48 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 48 ))
sparsemux_9_2_48_1_1_U1(
    .din0(inputBuf_fu_198),
    .din1(inputBuf_1_fu_202),
    .din2(inputBuf_2_fu_206),
    .din3(inputBuf_3_fu_210),
    .def(tmp_fu_310_p9),
    .sel(tmp_fu_310_p10),
    .dout(tmp_fu_310_p11)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U2(
    .din0(mul_ln115_fu_577_p0),
    .din1(local_temp_reg_1223),
    .dout(mul_ln115_fu_577_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U3(
    .din0(mul_ln115_1_fu_604_p0),
    .din1(local_temp_1_reg_1228),
    .dout(mul_ln115_1_fu_604_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U4(
    .din0(mul_ln115_2_fu_631_p0),
    .din1(local_temp_2_reg_1233),
    .dout(mul_ln115_2_fu_631_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U5(
    .din0(mul_ln115_3_fu_658_p0),
    .din1(local_temp_3_reg_1238),
    .dout(mul_ln115_3_fu_658_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U6(
    .din0(mul_ln115_4_fu_685_p0),
    .din1(local_temp_4_reg_1243),
    .dout(mul_ln115_4_fu_685_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U7(
    .din0(mul_ln115_5_fu_712_p0),
    .din1(local_temp_5_reg_1248),
    .dout(mul_ln115_5_fu_712_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U8(
    .din0(mul_ln115_6_fu_739_p0),
    .din1(local_temp_6_reg_1253),
    .dout(mul_ln115_6_fu_739_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U9(
    .din0(mul_ln115_7_fu_766_p0),
    .din1(local_temp_7_reg_1258),
    .dout(mul_ln115_7_fu_766_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U10(
    .din0(mul_ln115_8_fu_793_p0),
    .din1(local_temp_8_reg_1263),
    .dout(mul_ln115_8_fu_793_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U11(
    .din0(mul_ln115_9_fu_820_p0),
    .din1(local_temp_9_reg_1268),
    .dout(mul_ln115_9_fu_820_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U12(
    .din0(mul_ln115_10_fu_847_p0),
    .din1(local_temp_10_reg_1273),
    .dout(mul_ln115_10_fu_847_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U13(
    .din0(mul_ln115_11_fu_874_p0),
    .din1(local_temp_11_reg_1278),
    .dout(mul_ln115_11_fu_874_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U14(
    .din0(mul_ln115_12_fu_901_p0),
    .din1(local_temp_12_reg_1283),
    .dout(mul_ln115_12_fu_901_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U15(
    .din0(mul_ln115_13_fu_928_p0),
    .din1(local_temp_13_reg_1288),
    .dout(mul_ln115_13_fu_928_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U16(
    .din0(mul_ln115_14_fu_951_p0),
    .din1(local_temp_14_reg_1293),
    .dout(mul_ln115_14_fu_951_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U17(
    .din0(mul_ln115_15_fu_978_p0),
    .din1(local_temp_15_reg_1298),
    .dout(mul_ln115_15_fu_978_p2)
);

MVAU_hls_4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd0) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_237 <= tmp_fu_310_p11;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == 
    ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd3)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_237 <= in0_V_TDATA;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_237 <= ap_phi_reg_pp0_iter0_inElem_reg_237;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if ((icmp_ln249_fu_276_p2 == 1'd0)) begin
            i_fu_190 <= i_2_fu_282_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_190 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_276_p2 == 1'd0) & (icmp_ln290_fu_520_p2 == 1'd1))) begin
            nf_fu_214 <= nf_5_fu_543_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_214 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_276_p2 == 1'd0) & (icmp_ln290_fu_520_p2 == 1'd1))) begin
            sf_fu_186 <= 32'd0;
        end else if (((icmp_ln249_fu_276_p2 == 1'd0) & (icmp_ln290_fu_520_p2 == 1'd0))) begin
            sf_fu_186 <= sf_2_fu_514_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_186 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_ln169_10_reg_1327 <= add_ln169_10_fu_1046_p2;
        add_ln169_12_reg_1332 <= add_ln169_12_fu_1062_p2;
        add_ln169_1_reg_1312 <= add_ln169_1_fu_988_p2;
        add_ln169_5_reg_1317 <= add_ln169_5_fu_1014_p2;
        add_ln169_9_reg_1322 <= add_ln169_9_fu_1040_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_1193_pp0_iter1_reg <= icmp_ln249_reg_1193;
        icmp_ln272_reg_1218_pp0_iter1_reg <= icmp_ln272_reg_1218;
        icmp_ln290_reg_1303_pp0_iter1_reg <= icmp_ln290_reg_1303;
        mul_ln115_13_reg_1307 <= mul_ln115_13_fu_928_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_1193 <= icmp_ln249_fu_276_p2;
        icmp_ln272_reg_1218 <= icmp_ln272_fu_354_p2;
        icmp_ln290_reg_1303 <= icmp_ln290_fu_520_p2;
        local_temp_10_reg_1273 <= {{in1_V_TDATA[21:20]}};
        local_temp_11_reg_1278 <= {{in1_V_TDATA[23:22]}};
        local_temp_12_reg_1283 <= {{in1_V_TDATA[25:24]}};
        local_temp_13_reg_1288 <= {{in1_V_TDATA[27:26]}};
        local_temp_14_reg_1293 <= {{in1_V_TDATA[29:28]}};
        local_temp_15_reg_1298 <= {{in1_V_TDATA[31:30]}};
        local_temp_1_reg_1228 <= {{in1_V_TDATA[3:2]}};
        local_temp_2_reg_1233 <= {{in1_V_TDATA[5:4]}};
        local_temp_3_reg_1238 <= {{in1_V_TDATA[7:6]}};
        local_temp_4_reg_1243 <= {{in1_V_TDATA[9:8]}};
        local_temp_5_reg_1248 <= {{in1_V_TDATA[11:10]}};
        local_temp_6_reg_1253 <= {{in1_V_TDATA[13:12]}};
        local_temp_7_reg_1258 <= {{in1_V_TDATA[15:14]}};
        local_temp_8_reg_1263 <= {{in1_V_TDATA[17:16]}};
        local_temp_9_reg_1268 <= {{in1_V_TDATA[19:18]}};
        local_temp_reg_1223 <= local_temp_fu_360_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln249_reg_1193_pp0_iter1_reg == 1'd0))) begin
        empty_fu_194 <= outElem_fu_1130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln249_reg_1193_pp0_iter2_reg <= icmp_ln249_reg_1193_pp0_iter1_reg;
        icmp_ln290_reg_1303_pp0_iter2_reg <= icmp_ln290_reg_1303_pp0_iter1_reg;
        outElem_reg_1337 <= outElem_fu_1130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd1))) begin
        inputBuf_1_fu_202 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd2))) begin
        inputBuf_2_fu_206 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd3))) begin
        inputBuf_3_fu_210 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_288_p1 == 2'd0))) begin
        inputBuf_fu_198 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_276_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_190;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_214;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_186;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TDATA_blk_n = in1_V_TVALID;
    end else begin
        in1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TREADY = 1'b1;
    end else begin
        in1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op239_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_predicate_op239_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out0_V_TVALID = 1'b1;
    end else begin
        out0_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (icmp_ln249_reg_1193_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln169_10_fu_1046_p2 = ($signed(sext_ln257_4_fu_691_p1) + $signed(sext_ln257_3_fu_664_p1));

assign add_ln169_11_fu_1052_p2 = ($signed(sext_ln257_5_fu_718_p1) + $signed(sext_ln169_1_fu_984_p1));

assign add_ln169_12_fu_1062_p2 = ($signed(sext_ln169_10_fu_1058_p1) + $signed(sext_ln257_6_fu_745_p1));

assign add_ln169_13_fu_1114_p2 = ($signed(sext_ln169_11_fu_1111_p1) + $signed(sext_ln169_9_fu_1108_p1));

assign add_ln169_14_fu_1120_p2 = ($signed(add_ln169_13_fu_1114_p2) + $signed(sext_ln169_8_fu_1105_p1));

assign add_ln169_1_fu_988_p2 = ($signed(sext_ln257_13_fu_957_p1) + $signed(sext_ln257_12_fu_907_p1));

assign add_ln169_2_fu_1090_p2 = ($signed(sext_ln169_2_fu_1087_p1) + $signed(add_ln169_fu_1081_p2));

assign add_ln169_3_fu_994_p2 = ($signed(sext_ln257_11_fu_880_p1) + $signed(sext_ln257_8_fu_799_p1));

assign add_ln169_4_fu_1004_p2 = ($signed(sext_ln257_7_fu_772_p1) + $signed(sext_ln257_10_fu_853_p1));

assign add_ln169_5_fu_1014_p2 = ($signed(sext_ln169_4_fu_1010_p1) + $signed(sext_ln169_3_fu_1000_p1));

assign add_ln169_6_fu_1099_p2 = ($signed(sext_ln169_5_fu_1096_p1) + $signed(add_ln169_2_fu_1090_p2));

assign add_ln169_7_fu_1020_p2 = ($signed(sext_ln257_9_fu_826_p1) + $signed(sext_ln257_fu_583_p1));

assign add_ln169_8_fu_1030_p2 = ($signed(sext_ln257_2_fu_637_p1) + $signed(sext_ln257_1_fu_610_p1));

assign add_ln169_9_fu_1040_p2 = ($signed(sext_ln169_7_fu_1036_p1) + $signed(sext_ln169_6_fu_1026_p1));

assign add_ln169_fu_1081_p2 = ($signed(select_ln272_fu_1071_p3) + $signed(sext_ln169_fu_1078_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_276_p2 == 1'd0)) | ((ap_predicate_op40_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op239_write_state4 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op239_write_state4 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_105 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_237 = 'bx;

always @ (*) begin
    ap_predicate_op239_write_state4 = ((icmp_ln290_reg_1303_pp0_iter2_reg == 1'd1) & (icmp_ln249_reg_1193_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op40_read_state1 = ((icmp_ln253_fu_292_p2 == 1'd1) & (icmp_ln249_fu_276_p2 == 1'd0));
end

assign i_2_fu_282_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign icmp_ln249_fu_276_p2 = ((ap_sig_allocacmp_i_1 == 8'd172) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_292_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_354_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_520_p2 = ((sf_2_fu_514_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_537_p2 = ((nf_4_fu_531_p2 == 32'd43) ? 1'b1 : 1'b0);

assign local_temp_fu_360_p1 = in1_V_TDATA[1:0];

assign mul_ln115_10_fu_847_p0 = mul_ln115_10_fu_847_p00;

assign mul_ln115_10_fu_847_p00 = r_10_fu_830_p4;

assign mul_ln115_11_fu_874_p0 = mul_ln115_11_fu_874_p00;

assign mul_ln115_11_fu_874_p00 = r_11_fu_857_p4;

assign mul_ln115_12_fu_901_p0 = mul_ln115_12_fu_901_p00;

assign mul_ln115_12_fu_901_p00 = r_12_fu_884_p4;

assign mul_ln115_13_fu_928_p0 = mul_ln115_13_fu_928_p00;

assign mul_ln115_13_fu_928_p00 = r_13_fu_911_p4;

assign mul_ln115_14_fu_951_p0 = mul_ln115_14_fu_951_p00;

assign mul_ln115_14_fu_951_p00 = r_14_fu_934_p4;

assign mul_ln115_15_fu_978_p0 = mul_ln115_15_fu_978_p00;

assign mul_ln115_15_fu_978_p00 = r_15_fu_961_p4;

assign mul_ln115_1_fu_604_p0 = mul_ln115_1_fu_604_p00;

assign mul_ln115_1_fu_604_p00 = r_1_fu_587_p4;

assign mul_ln115_2_fu_631_p0 = mul_ln115_2_fu_631_p00;

assign mul_ln115_2_fu_631_p00 = r_2_fu_614_p4;

assign mul_ln115_3_fu_658_p0 = mul_ln115_3_fu_658_p00;

assign mul_ln115_3_fu_658_p00 = r_3_fu_641_p4;

assign mul_ln115_4_fu_685_p0 = mul_ln115_4_fu_685_p00;

assign mul_ln115_4_fu_685_p00 = r_4_fu_668_p4;

assign mul_ln115_5_fu_712_p0 = mul_ln115_5_fu_712_p00;

assign mul_ln115_5_fu_712_p00 = r_5_fu_695_p4;

assign mul_ln115_6_fu_739_p0 = mul_ln115_6_fu_739_p00;

assign mul_ln115_6_fu_739_p00 = r_6_fu_722_p4;

assign mul_ln115_7_fu_766_p0 = mul_ln115_7_fu_766_p00;

assign mul_ln115_7_fu_766_p00 = r_7_fu_749_p4;

assign mul_ln115_8_fu_793_p0 = mul_ln115_8_fu_793_p00;

assign mul_ln115_8_fu_793_p00 = r_8_fu_776_p4;

assign mul_ln115_9_fu_820_p0 = mul_ln115_9_fu_820_p00;

assign mul_ln115_9_fu_820_p00 = r_9_fu_803_p4;

assign mul_ln115_fu_577_p0 = mul_ln115_fu_577_p00;

assign mul_ln115_fu_577_p00 = r_fu_566_p1;

assign nf_4_fu_531_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_543_p3 = ((icmp_ln302_fu_537_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_531_p2);

assign out0_V_TDATA = outElem_reg_1337;

assign outElem_fu_1130_p2 = ($signed(sext_ln169_12_fu_1126_p1) + $signed(add_ln169_6_fu_1099_p2));

assign r_10_fu_830_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[32:30]}};

assign r_11_fu_857_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[35:33]}};

assign r_12_fu_884_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[38:36]}};

assign r_13_fu_911_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[41:39]}};

assign r_14_fu_934_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[44:42]}};

assign r_15_fu_961_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[47:45]}};

assign r_1_fu_587_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[5:3]}};

assign r_2_fu_614_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[8:6]}};

assign r_3_fu_641_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[11:9]}};

assign r_4_fu_668_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[14:12]}};

assign r_5_fu_695_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[17:15]}};

assign r_6_fu_722_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[20:18]}};

assign r_7_fu_749_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[23:21]}};

assign r_8_fu_776_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[26:24]}};

assign r_9_fu_803_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_237[29:27]}};

assign r_fu_566_p1 = ap_phi_reg_pp0_iter1_inElem_reg_237[2:0];

assign select_ln272_fu_1071_p3 = ((icmp_ln272_reg_1218_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : empty_fu_194);

assign sext_ln169_10_fu_1058_p1 = $signed(add_ln169_11_fu_1052_p2);

assign sext_ln169_11_fu_1111_p1 = $signed(add_ln169_12_reg_1332);

assign sext_ln169_12_fu_1126_p1 = $signed(add_ln169_14_fu_1120_p2);

assign sext_ln169_1_fu_984_p1 = mul_ln115_15_fu_978_p2;

assign sext_ln169_2_fu_1087_p1 = $signed(add_ln169_1_reg_1312);

assign sext_ln169_3_fu_1000_p1 = $signed(add_ln169_3_fu_994_p2);

assign sext_ln169_4_fu_1010_p1 = $signed(add_ln169_4_fu_1004_p2);

assign sext_ln169_5_fu_1096_p1 = $signed(add_ln169_5_reg_1317);

assign sext_ln169_6_fu_1026_p1 = $signed(add_ln169_7_fu_1020_p2);

assign sext_ln169_7_fu_1036_p1 = $signed(add_ln169_8_fu_1030_p2);

assign sext_ln169_8_fu_1105_p1 = $signed(add_ln169_9_reg_1322);

assign sext_ln169_9_fu_1108_p1 = $signed(add_ln169_10_reg_1327);

assign sext_ln169_fu_1078_p1 = mul_ln115_13_reg_1307;

assign sext_ln257_10_fu_853_p1 = mul_ln115_10_fu_847_p2;

assign sext_ln257_11_fu_880_p1 = mul_ln115_11_fu_874_p2;

assign sext_ln257_12_fu_907_p1 = mul_ln115_12_fu_901_p2;

assign sext_ln257_13_fu_957_p1 = mul_ln115_14_fu_951_p2;

assign sext_ln257_1_fu_610_p1 = mul_ln115_1_fu_604_p2;

assign sext_ln257_2_fu_637_p1 = mul_ln115_2_fu_631_p2;

assign sext_ln257_3_fu_664_p1 = mul_ln115_3_fu_658_p2;

assign sext_ln257_4_fu_691_p1 = mul_ln115_4_fu_685_p2;

assign sext_ln257_5_fu_718_p1 = mul_ln115_5_fu_712_p2;

assign sext_ln257_6_fu_745_p1 = mul_ln115_6_fu_739_p2;

assign sext_ln257_7_fu_772_p1 = mul_ln115_7_fu_766_p2;

assign sext_ln257_8_fu_799_p1 = mul_ln115_8_fu_793_p2;

assign sext_ln257_9_fu_826_p1 = mul_ln115_9_fu_820_p2;

assign sext_ln257_fu_583_p1 = mul_ln115_fu_577_p2;

assign sf_2_fu_514_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_310_p10 = ap_sig_allocacmp_sf_1[1:0];

assign tmp_fu_310_p9 = 'bx;

assign trunc_ln242_fu_288_p1 = ap_sig_allocacmp_sf_1[1:0];

endmodule //MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch
