// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        in1_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID,
        in1_V_TDATA,
        in1_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   in1_V_TVALID;
input   out0_V_TREADY;
input  [23:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [31:0] out0_V_TDATA;
output   out0_V_TVALID;
input  [15:0] in1_V_TDATA;
output   in1_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out0_V_TVALID;
reg in1_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] icmp_ln249_fu_248_p2;
wire   [0:0] icmp_ln253_fu_264_p2;
reg    ap_predicate_op48_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln249_reg_871;
reg   [0:0] icmp_ln249_reg_871_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_945;
reg   [0:0] icmp_ln290_reg_945_pp0_iter2_reg;
reg    ap_predicate_op169_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
reg    in1_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_871_pp0_iter1_reg;
wire   [2:0] trunc_ln242_fu_260_p1;
wire   [23:0] tmp_fu_294_p19;
wire   [0:0] icmp_ln272_fu_374_p2;
reg   [0:0] icmp_ln272_reg_900;
reg   [0:0] icmp_ln272_reg_900_pp0_iter1_reg;
wire   [1:0] local_temp_fu_380_p1;
reg  signed [1:0] local_temp_reg_905;
reg  signed [1:0] local_temp_1_reg_910;
reg  signed [1:0] local_temp_2_reg_915;
reg  signed [1:0] local_temp_3_reg_920;
reg  signed [1:0] local_temp_4_reg_925;
reg  signed [1:0] local_temp_5_reg_930;
reg  signed [1:0] local_temp_6_reg_935;
reg  signed [1:0] local_temp_7_reg_940;
wire   [0:0] icmp_ln290_fu_460_p2;
reg   [0:0] icmp_ln290_reg_945_pp0_iter1_reg;
wire  signed [4:0] mul_ln115_5_fu_652_p2;
reg  signed [4:0] mul_ln115_5_reg_949;
wire   [5:0] add_ln169_1_fu_712_p2;
reg   [5:0] add_ln169_1_reg_954;
wire   [5:0] add_ln169_3_fu_718_p2;
reg   [5:0] add_ln169_3_reg_959;
wire   [6:0] add_ln169_5_fu_734_p2;
reg   [6:0] add_ln169_5_reg_964;
wire   [31:0] outElem_fu_784_p2;
reg   [31:0] outElem_reg_969;
wire   [23:0] ap_phi_reg_pp0_iter0_inElem_reg_201;
reg   [23:0] ap_phi_reg_pp0_iter1_inElem_reg_201;
reg   [31:0] sf_fu_134;
wire   [31:0] sf_2_fu_454_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [8:0] i_fu_138;
wire   [8:0] i_2_fu_254_p2;
reg   [8:0] ap_sig_allocacmp_i_1;
reg   [31:0] empty_fu_142;
reg   [23:0] inputBuf_fu_146;
reg   [23:0] inputBuf_1_fu_150;
reg   [23:0] inputBuf_2_fu_154;
reg   [23:0] inputBuf_3_fu_158;
reg   [23:0] inputBuf_4_fu_162;
reg   [23:0] inputBuf_5_fu_166;
reg   [23:0] inputBuf_6_fu_170;
reg   [23:0] inputBuf_7_fu_174;
reg   [31:0] nf_fu_178;
wire   [31:0] nf_5_fu_483_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [23:0] tmp_fu_294_p17;
wire   [2:0] tmp_fu_294_p18;
wire   [31:0] nf_4_fu_471_p2;
wire   [0:0] icmp_ln302_fu_477_p2;
wire   [2:0] r_fu_506_p1;
wire   [2:0] mul_ln115_fu_517_p0;
wire  signed [4:0] mul_ln115_fu_517_p2;
wire   [2:0] r_1_fu_527_p4;
wire   [2:0] mul_ln115_1_fu_544_p0;
wire  signed [4:0] mul_ln115_1_fu_544_p2;
wire   [2:0] r_2_fu_554_p4;
wire   [2:0] mul_ln115_2_fu_571_p0;
wire  signed [4:0] mul_ln115_2_fu_571_p2;
wire   [2:0] r_3_fu_581_p4;
wire   [2:0] mul_ln115_3_fu_598_p0;
wire  signed [4:0] mul_ln115_3_fu_598_p2;
wire   [2:0] r_4_fu_608_p4;
wire   [2:0] mul_ln115_4_fu_625_p0;
wire  signed [4:0] mul_ln115_4_fu_625_p2;
wire   [2:0] r_5_fu_635_p4;
wire   [2:0] mul_ln115_5_fu_652_p0;
wire   [2:0] r_6_fu_658_p4;
wire   [2:0] mul_ln115_6_fu_675_p0;
wire  signed [4:0] mul_ln115_6_fu_675_p2;
wire   [2:0] r_7_fu_685_p4;
wire   [2:0] mul_ln115_7_fu_702_p0;
wire  signed [4:0] mul_ln115_7_fu_702_p2;
wire  signed [5:0] sext_ln257_5_fu_681_p1;
wire  signed [5:0] sext_ln257_4_fu_631_p1;
wire  signed [5:0] sext_ln257_3_fu_604_p1;
wire  signed [5:0] sext_ln257_fu_523_p1;
wire  signed [5:0] sext_ln257_1_fu_550_p1;
wire  signed [5:0] sext_ln169_1_fu_708_p1;
wire   [5:0] add_ln169_4_fu_724_p2;
wire  signed [6:0] sext_ln169_4_fu_730_p1;
wire  signed [6:0] sext_ln257_2_fu_577_p1;
wire   [31:0] select_ln272_fu_743_p3;
wire  signed [31:0] sext_ln169_fu_750_p1;
wire  signed [31:0] sext_ln169_2_fu_759_p1;
wire   [31:0] add_ln169_fu_753_p2;
wire  signed [7:0] sext_ln169_5_fu_771_p1;
wire  signed [7:0] sext_ln169_3_fu_768_p1;
wire   [7:0] add_ln169_6_fu_774_p2;
wire  signed [31:0] sext_ln169_6_fu_780_p1;
wire   [31:0] add_ln169_2_fu_762_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_start_int;
wire   [4:0] mul_ln115_1_fu_544_p00;
wire   [4:0] mul_ln115_2_fu_571_p00;
wire   [4:0] mul_ln115_3_fu_598_p00;
wire   [4:0] mul_ln115_4_fu_625_p00;
wire   [4:0] mul_ln115_5_fu_652_p00;
wire   [4:0] mul_ln115_6_fu_675_p00;
wire   [4:0] mul_ln115_7_fu_702_p00;
wire   [4:0] mul_ln115_fu_517_p00;
reg    ap_condition_105;
wire   [2:0] tmp_fu_294_p1;
wire   [2:0] tmp_fu_294_p3;
wire   [2:0] tmp_fu_294_p5;
wire   [2:0] tmp_fu_294_p7;
wire  signed [2:0] tmp_fu_294_p9;
wire  signed [2:0] tmp_fu_294_p11;
wire  signed [2:0] tmp_fu_294_p13;
wire  signed [2:0] tmp_fu_294_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 sf_fu_134 = 32'd0;
#0 i_fu_138 = 9'd0;
#0 empty_fu_142 = 32'd0;
#0 inputBuf_fu_146 = 24'd0;
#0 inputBuf_1_fu_150 = 24'd0;
#0 inputBuf_2_fu_154 = 24'd0;
#0 inputBuf_3_fu_158 = 24'd0;
#0 inputBuf_4_fu_162 = 24'd0;
#0 inputBuf_5_fu_166 = 24'd0;
#0 inputBuf_6_fu_170 = 24'd0;
#0 inputBuf_7_fu_174 = 24'd0;
#0 nf_fu_178 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_4_sparsemux_17_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 24 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 24 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_17_3_24_1_1_U1(
    .din0(inputBuf_fu_146),
    .din1(inputBuf_1_fu_150),
    .din2(inputBuf_2_fu_154),
    .din3(inputBuf_3_fu_158),
    .din4(inputBuf_4_fu_162),
    .din5(inputBuf_5_fu_166),
    .din6(inputBuf_6_fu_170),
    .din7(inputBuf_7_fu_174),
    .def(tmp_fu_294_p17),
    .sel(tmp_fu_294_p18),
    .dout(tmp_fu_294_p19)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U2(
    .din0(mul_ln115_fu_517_p0),
    .din1(local_temp_reg_905),
    .dout(mul_ln115_fu_517_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U3(
    .din0(mul_ln115_1_fu_544_p0),
    .din1(local_temp_1_reg_910),
    .dout(mul_ln115_1_fu_544_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U4(
    .din0(mul_ln115_2_fu_571_p0),
    .din1(local_temp_2_reg_915),
    .dout(mul_ln115_2_fu_571_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U5(
    .din0(mul_ln115_3_fu_598_p0),
    .din1(local_temp_3_reg_920),
    .dout(mul_ln115_3_fu_598_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U6(
    .din0(mul_ln115_4_fu_625_p0),
    .din1(local_temp_4_reg_925),
    .dout(mul_ln115_4_fu_625_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U7(
    .din0(mul_ln115_5_fu_652_p0),
    .din1(local_temp_5_reg_930),
    .dout(mul_ln115_5_fu_652_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U8(
    .din0(mul_ln115_6_fu_675_p0),
    .din1(local_temp_6_reg_935),
    .dout(mul_ln115_6_fu_675_p2)
);

MVAU_hls_4_mul_3ns_2s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 5 ))
mul_3ns_2s_5_1_1_U9(
    .din0(mul_ln115_7_fu_702_p0),
    .din1(local_temp_7_reg_940),
    .dout(mul_ln115_7_fu_702_p2)
);

MVAU_hls_4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd0) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_201 <= tmp_fu_294_p19;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd6)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == 
    ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd3)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd4)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) 
    & (trunc_ln242_fu_260_p1 == 3'd5)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd7)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_201 <= in0_V_TDATA;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_201 <= ap_phi_reg_pp0_iter0_inElem_reg_201;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if ((icmp_ln249_fu_248_p2 == 1'd0)) begin
            i_fu_138 <= i_2_fu_254_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_138 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_248_p2 == 1'd0) & (icmp_ln290_fu_460_p2 == 1'd1))) begin
            nf_fu_178 <= nf_5_fu_483_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_178 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_248_p2 == 1'd0) & (icmp_ln290_fu_460_p2 == 1'd1))) begin
            sf_fu_134 <= 32'd0;
        end else if (((icmp_ln249_fu_248_p2 == 1'd0) & (icmp_ln290_fu_460_p2 == 1'd0))) begin
            sf_fu_134 <= sf_2_fu_454_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_134 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_ln169_1_reg_954 <= add_ln169_1_fu_712_p2;
        add_ln169_3_reg_959 <= add_ln169_3_fu_718_p2;
        add_ln169_5_reg_964 <= add_ln169_5_fu_734_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_871_pp0_iter1_reg <= icmp_ln249_reg_871;
        icmp_ln272_reg_900_pp0_iter1_reg <= icmp_ln272_reg_900;
        icmp_ln290_reg_945_pp0_iter1_reg <= icmp_ln290_reg_945;
        mul_ln115_5_reg_949 <= mul_ln115_5_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_871 <= icmp_ln249_fu_248_p2;
        icmp_ln272_reg_900 <= icmp_ln272_fu_374_p2;
        icmp_ln290_reg_945 <= icmp_ln290_fu_460_p2;
        local_temp_1_reg_910 <= {{in1_V_TDATA[3:2]}};
        local_temp_2_reg_915 <= {{in1_V_TDATA[5:4]}};
        local_temp_3_reg_920 <= {{in1_V_TDATA[7:6]}};
        local_temp_4_reg_925 <= {{in1_V_TDATA[9:8]}};
        local_temp_5_reg_930 <= {{in1_V_TDATA[11:10]}};
        local_temp_6_reg_935 <= {{in1_V_TDATA[13:12]}};
        local_temp_7_reg_940 <= {{in1_V_TDATA[15:14]}};
        local_temp_reg_905 <= local_temp_fu_380_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln249_reg_871_pp0_iter1_reg == 1'd0))) begin
        empty_fu_142 <= outElem_fu_784_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln249_reg_871_pp0_iter2_reg <= icmp_ln249_reg_871_pp0_iter1_reg;
        icmp_ln290_reg_945_pp0_iter2_reg <= icmp_ln290_reg_945_pp0_iter1_reg;
        outElem_reg_969 <= outElem_fu_784_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd1))) begin
        inputBuf_1_fu_150 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd2))) begin
        inputBuf_2_fu_154 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd3))) begin
        inputBuf_3_fu_158 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd4))) begin
        inputBuf_4_fu_162 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd5))) begin
        inputBuf_5_fu_166 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd6))) begin
        inputBuf_6_fu_170 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd7))) begin
        inputBuf_7_fu_174 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_260_p1 == 3'd0))) begin
        inputBuf_fu_146 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_248_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_138;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_178;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_134;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op48_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (ap_predicate_op48_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TDATA_blk_n = in1_V_TVALID;
    end else begin
        in1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TREADY = 1'b1;
    end else begin
        in1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op169_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_predicate_op169_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out0_V_TVALID = 1'b1;
    end else begin
        out0_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (icmp_ln249_reg_871_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln169_1_fu_712_p2 = ($signed(sext_ln257_5_fu_681_p1) + $signed(sext_ln257_4_fu_631_p1));

assign add_ln169_2_fu_762_p2 = ($signed(sext_ln169_2_fu_759_p1) + $signed(add_ln169_fu_753_p2));

assign add_ln169_3_fu_718_p2 = ($signed(sext_ln257_3_fu_604_p1) + $signed(sext_ln257_fu_523_p1));

assign add_ln169_4_fu_724_p2 = ($signed(sext_ln257_1_fu_550_p1) + $signed(sext_ln169_1_fu_708_p1));

assign add_ln169_5_fu_734_p2 = ($signed(sext_ln169_4_fu_730_p1) + $signed(sext_ln257_2_fu_577_p1));

assign add_ln169_6_fu_774_p2 = ($signed(sext_ln169_5_fu_771_p1) + $signed(sext_ln169_3_fu_768_p1));

assign add_ln169_fu_753_p2 = ($signed(select_ln272_fu_743_p3) + $signed(sext_ln169_fu_750_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_248_p2 == 1'd0)) | ((ap_predicate_op48_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op169_write_state4 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op169_write_state4 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_105 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_201 = 'bx;

always @ (*) begin
    ap_predicate_op169_write_state4 = ((icmp_ln290_reg_945_pp0_iter2_reg == 1'd1) & (icmp_ln249_reg_871_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op48_read_state1 = ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_248_p2 == 1'd0));
end

assign i_2_fu_254_p2 = (ap_sig_allocacmp_i_1 + 9'd1);

assign icmp_ln249_fu_248_p2 = ((ap_sig_allocacmp_i_1 == 9'd344) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_264_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_374_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_460_p2 = ((sf_2_fu_454_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_477_p2 = ((nf_4_fu_471_p2 == 32'd43) ? 1'b1 : 1'b0);

assign local_temp_fu_380_p1 = in1_V_TDATA[1:0];

assign mul_ln115_1_fu_544_p0 = mul_ln115_1_fu_544_p00;

assign mul_ln115_1_fu_544_p00 = r_1_fu_527_p4;

assign mul_ln115_2_fu_571_p0 = mul_ln115_2_fu_571_p00;

assign mul_ln115_2_fu_571_p00 = r_2_fu_554_p4;

assign mul_ln115_3_fu_598_p0 = mul_ln115_3_fu_598_p00;

assign mul_ln115_3_fu_598_p00 = r_3_fu_581_p4;

assign mul_ln115_4_fu_625_p0 = mul_ln115_4_fu_625_p00;

assign mul_ln115_4_fu_625_p00 = r_4_fu_608_p4;

assign mul_ln115_5_fu_652_p0 = mul_ln115_5_fu_652_p00;

assign mul_ln115_5_fu_652_p00 = r_5_fu_635_p4;

assign mul_ln115_6_fu_675_p0 = mul_ln115_6_fu_675_p00;

assign mul_ln115_6_fu_675_p00 = r_6_fu_658_p4;

assign mul_ln115_7_fu_702_p0 = mul_ln115_7_fu_702_p00;

assign mul_ln115_7_fu_702_p00 = r_7_fu_685_p4;

assign mul_ln115_fu_517_p0 = mul_ln115_fu_517_p00;

assign mul_ln115_fu_517_p00 = r_fu_506_p1;

assign nf_4_fu_471_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_483_p3 = ((icmp_ln302_fu_477_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_471_p2);

assign out0_V_TDATA = outElem_reg_969;

assign outElem_fu_784_p2 = ($signed(sext_ln169_6_fu_780_p1) + $signed(add_ln169_2_fu_762_p2));

assign r_1_fu_527_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[5:3]}};

assign r_2_fu_554_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[8:6]}};

assign r_3_fu_581_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[11:9]}};

assign r_4_fu_608_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[14:12]}};

assign r_5_fu_635_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[17:15]}};

assign r_6_fu_658_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[20:18]}};

assign r_7_fu_685_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_201[23:21]}};

assign r_fu_506_p1 = ap_phi_reg_pp0_iter1_inElem_reg_201[2:0];

assign select_ln272_fu_743_p3 = ((icmp_ln272_reg_900_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : empty_fu_142);

assign sext_ln169_1_fu_708_p1 = mul_ln115_7_fu_702_p2;

assign sext_ln169_2_fu_759_p1 = $signed(add_ln169_1_reg_954);

assign sext_ln169_3_fu_768_p1 = $signed(add_ln169_3_reg_959);

assign sext_ln169_4_fu_730_p1 = $signed(add_ln169_4_fu_724_p2);

assign sext_ln169_5_fu_771_p1 = $signed(add_ln169_5_reg_964);

assign sext_ln169_6_fu_780_p1 = $signed(add_ln169_6_fu_774_p2);

assign sext_ln169_fu_750_p1 = mul_ln115_5_reg_949;

assign sext_ln257_1_fu_550_p1 = mul_ln115_1_fu_544_p2;

assign sext_ln257_2_fu_577_p1 = mul_ln115_2_fu_571_p2;

assign sext_ln257_3_fu_604_p1 = mul_ln115_3_fu_598_p2;

assign sext_ln257_4_fu_631_p1 = mul_ln115_4_fu_625_p2;

assign sext_ln257_5_fu_681_p1 = mul_ln115_6_fu_675_p2;

assign sext_ln257_fu_523_p1 = mul_ln115_fu_517_p2;

assign sf_2_fu_454_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_294_p17 = 'bx;

assign tmp_fu_294_p18 = ap_sig_allocacmp_sf_1[2:0];

assign trunc_ln242_fu_260_p1 = ap_sig_allocacmp_sf_1[2:0];

endmodule //MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch
