// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="StreamingDataWidthConverter_hls_0_StreamingDataWidthConverter_hls_0,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.258000,HLS_SYN_LAT=328,HLS_SYN_TPT=327,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=362,HLS_SYN_LUT=629,HLS_VERSION=2023_2}" *)

module StreamingDataWidthConverter_hls_0 (
        in0_V_TDATA,
        out0_V_TDATA,
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        in0_V_TREADY,
        out0_V_TVALID,
        out0_V_TREADY
);


input  [39:0] in0_V_TDATA;
output  [55:0] out0_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
output   in0_V_TREADY;
output   out0_V_TVALID;
input   out0_V_TREADY;

 reg    ap_rst_n_inv;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_start;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_done;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_continue;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_idle;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_ready;
wire   [107:0] StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_din;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_write;
wire    StreamingDataWidthConverter_Batch_36u_108u_324u_U0_in0_V_TREADY;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_start;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_done;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_continue;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_idle;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_ready;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_intermediate_read;
wire   [55:0] StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TDATA;
wire    StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TVALID;
wire    intermediate_full_n;
wire   [107:0] intermediate_dout;
wire   [2:0] intermediate_num_data_valid;
wire   [2:0] intermediate_fifo_cap;
wire    intermediate_empty_n;

StreamingDataWidthConverter_hls_0_StreamingDataWidthConverter_Batch_36u_108u_324u_s StreamingDataWidthConverter_Batch_36u_108u_324u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_start),
    .ap_done(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_done),
    .ap_continue(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_continue),
    .ap_idle(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_idle),
    .ap_ready(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_ready),
    .in0_V_TVALID(in0_V_TVALID),
    .intermediate_din(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_din),
    .intermediate_num_data_valid(intermediate_num_data_valid),
    .intermediate_fifo_cap(intermediate_fifo_cap),
    .intermediate_full_n(intermediate_full_n),
    .intermediate_write(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_write),
    .in0_V_TDATA(in0_V_TDATA),
    .in0_V_TREADY(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_in0_V_TREADY)
);

StreamingDataWidthConverter_hls_0_StreamingDataWidthConverter_Batch_108u_54u_108u_s StreamingDataWidthConverter_Batch_108u_54u_108u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_start),
    .ap_done(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_done),
    .ap_continue(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_continue),
    .ap_idle(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_idle),
    .ap_ready(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_ready),
    .intermediate_dout(intermediate_dout),
    .intermediate_num_data_valid(intermediate_num_data_valid),
    .intermediate_fifo_cap(intermediate_fifo_cap),
    .intermediate_empty_n(intermediate_empty_n),
    .intermediate_read(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_intermediate_read),
    .out0_V_TREADY(out0_V_TREADY),
    .out0_V_TDATA(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TDATA),
    .out0_V_TVALID(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TVALID)
);

StreamingDataWidthConverter_hls_0_fifo_w108_d2_S intermediate_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_din),
    .if_full_n(intermediate_full_n),
    .if_write(StreamingDataWidthConverter_Batch_36u_108u_324u_U0_intermediate_write),
    .if_dout(intermediate_dout),
    .if_num_data_valid(intermediate_num_data_valid),
    .if_fifo_cap(intermediate_fifo_cap),
    .if_empty_n(intermediate_empty_n),
    .if_read(StreamingDataWidthConverter_Batch_108u_54u_108u_U0_intermediate_read)
);

assign StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_continue = 1'b1;

assign StreamingDataWidthConverter_Batch_108u_54u_108u_U0_ap_start = 1'b1;

assign StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_continue = 1'b1;

assign StreamingDataWidthConverter_Batch_36u_108u_324u_U0_ap_start = 1'b1;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign in0_V_TREADY = StreamingDataWidthConverter_Batch_36u_108u_324u_U0_in0_V_TREADY;

assign out0_V_TDATA = StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TDATA;

assign out0_V_TVALID = StreamingDataWidthConverter_Batch_108u_54u_108u_U0_out0_V_TVALID;

endmodule //StreamingDataWidthConverter_hls_0
