// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Pool_hls_0_Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out0_V_TREADY;
input  [39:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [39:0] out0_V_TDATA;
output   out0_V_TVALID;

reg ap_idle;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln255_fu_145_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln255_reg_639;
reg   [0:0] ret_reg_715;
reg    ap_predicate_op82_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln255_reg_639_pp0_iter1_reg;
reg   [0:0] ret_reg_715_pp0_iter1_reg;
reg    ap_predicate_op86_write_state3;
wire    regslice_both_out0_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
wire   [2:0] trunc_ln258_fu_160_p1;
reg   [2:0] trunc_ln258_reg_643;
reg   [2:0] trunc_ln258_2_reg_649;
reg   [2:0] trunc_ln258_3_reg_655;
reg   [2:0] trunc_ln258_4_reg_661;
reg   [2:0] trunc_ln258_5_reg_667;
reg   [2:0] trunc_ln258_6_reg_673;
reg   [2:0] trunc_ln258_7_reg_679;
reg   [2:0] trunc_ln258_8_reg_685;
reg   [2:0] trunc_ln258_9_reg_691;
reg   [2:0] trunc_ln258_s_reg_697;
reg   [2:0] trunc_ln258_1_reg_703;
reg   [2:0] trunc_ln258_10_reg_709;
wire   [0:0] ret_fu_274_p3;
reg   [35:0] phi_ln257_fu_102;
wire   [35:0] select_ln255_fu_606_p3;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [35:0] ap_sig_allocacmp_phi_ln257_load;
reg   [7:0] i_fu_106;
wire   [7:0] i_2_fu_151_p2;
reg   [7:0] ap_sig_allocacmp_i_1;
reg   [2:0] empty_fu_110;
wire   [2:0] add_ln292_1_fu_296_p2;
reg   [2:0] ap_sig_allocacmp_p_load;
wire   [2:0] and_ln_fu_282_p3;
wire   [2:0] add_ln292_fu_290_p2;
wire   [2:0] trunc_ln224_fu_315_p1;
wire   [0:0] icmp_ln224_fu_319_p2;
wire   [2:0] trunc_ln224_1_fu_331_p4;
wire   [0:0] icmp_ln224_1_fu_341_p2;
wire   [2:0] trunc_ln224_2_fu_353_p4;
wire   [0:0] icmp_ln224_2_fu_363_p2;
wire   [2:0] trunc_ln224_3_fu_375_p4;
wire   [0:0] icmp_ln224_3_fu_385_p2;
wire   [2:0] trunc_ln224_4_fu_397_p4;
wire   [0:0] icmp_ln224_4_fu_407_p2;
wire   [2:0] trunc_ln224_5_fu_419_p4;
wire   [0:0] icmp_ln224_5_fu_429_p2;
wire   [2:0] trunc_ln224_6_fu_441_p4;
wire   [0:0] icmp_ln224_6_fu_451_p2;
wire   [2:0] trunc_ln224_7_fu_463_p4;
wire   [0:0] icmp_ln224_7_fu_473_p2;
wire   [2:0] trunc_ln224_8_fu_485_p4;
wire   [0:0] icmp_ln224_8_fu_495_p2;
wire   [2:0] trunc_ln224_9_fu_507_p4;
wire   [0:0] icmp_ln224_9_fu_517_p2;
wire   [2:0] trunc_ln224_s_fu_529_p4;
wire   [0:0] icmp_ln224_10_fu_539_p2;
wire   [2:0] trunc_ln224_10_fu_551_p4;
wire   [0:0] icmp_ln224_11_fu_561_p2;
wire   [2:0] select_ln127_11_fu_566_p3;
wire   [2:0] select_ln127_10_fu_544_p3;
wire   [2:0] select_ln127_9_fu_522_p3;
wire   [2:0] select_ln127_8_fu_500_p3;
wire   [2:0] select_ln127_7_fu_478_p3;
wire   [2:0] select_ln127_6_fu_456_p3;
wire   [2:0] select_ln127_5_fu_434_p3;
wire   [2:0] select_ln127_4_fu_412_p3;
wire   [2:0] select_ln127_3_fu_390_p3;
wire   [2:0] select_ln127_2_fu_368_p3;
wire   [2:0] select_ln127_1_fu_346_p3;
wire   [2:0] select_ln127_fu_324_p3;
wire   [35:0] or_ln127_s_fu_573_p13;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [39:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire   [39:0] out0_V_TDATA_int_regslice;
reg    out0_V_TVALID_int_regslice;
wire    out0_V_TREADY_int_regslice;
wire    regslice_both_out0_V_U_vld_out;
reg    ap_condition_106;
reg    ap_condition_133;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 phi_ln257_fu_102 = 36'd0;
#0 i_fu_106 = 8'd0;
#0 empty_fu_110 = 3'd0;
end

Pool_hls_0_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

Pool_hls_0_regslice_both #(
    .DataWidth( 40 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

Pool_hls_0_regslice_both #(
    .DataWidth( 40 ))
regslice_both_out0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out0_V_TDATA_int_regslice),
    .vld_in(out0_V_TVALID_int_regslice),
    .ack_in(out0_V_TREADY_int_regslice),
    .data_out(out0_V_TDATA),
    .vld_out(regslice_both_out0_V_U_vld_out),
    .ack_out(out0_V_TREADY),
    .apdone_blk(regslice_both_out0_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_106)) begin
        if ((icmp_ln255_fu_145_p2 == 1'd0)) begin
            empty_fu_110 <= add_ln292_1_fu_296_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_110 <= 3'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_106)) begin
        if ((icmp_ln255_fu_145_p2 == 1'd0)) begin
            i_fu_106 <= i_2_fu_151_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_106 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_133)) begin
        if ((icmp_ln255_reg_639 == 1'd0)) begin
            phi_ln257_fu_102 <= select_ln255_fu_606_p3;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            phi_ln257_fu_102 <= 36'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln255_reg_639 <= icmp_ln255_fu_145_p2;
        ret_reg_715 <= ap_sig_allocacmp_p_load[32'd2];
        trunc_ln258_10_reg_709 <= {{in0_V_TDATA_int_regslice[35:33]}};
        trunc_ln258_1_reg_703 <= {{in0_V_TDATA_int_regslice[32:30]}};
        trunc_ln258_2_reg_649 <= {{in0_V_TDATA_int_regslice[5:3]}};
        trunc_ln258_3_reg_655 <= {{in0_V_TDATA_int_regslice[8:6]}};
        trunc_ln258_4_reg_661 <= {{in0_V_TDATA_int_regslice[11:9]}};
        trunc_ln258_5_reg_667 <= {{in0_V_TDATA_int_regslice[14:12]}};
        trunc_ln258_6_reg_673 <= {{in0_V_TDATA_int_regslice[17:15]}};
        trunc_ln258_7_reg_679 <= {{in0_V_TDATA_int_regslice[20:18]}};
        trunc_ln258_8_reg_685 <= {{in0_V_TDATA_int_regslice[23:21]}};
        trunc_ln258_9_reg_691 <= {{in0_V_TDATA_int_regslice[26:24]}};
        trunc_ln258_reg_643 <= trunc_ln258_fu_160_p1;
        trunc_ln258_s_reg_697 <= {{in0_V_TDATA_int_regslice[29:27]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln255_reg_639_pp0_iter1_reg <= icmp_ln255_reg_639;
        ret_reg_715_pp0_iter1_reg <= ret_reg_715;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (icmp_ln255_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_106;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_load = 3'd2;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_110;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_phi_ln257_load = 36'd0;
    end else begin
        ap_sig_allocacmp_phi_ln257_load = phi_ln257_fu_102;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start_int == 1'b1) & (icmp_ln255_fu_145_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (icmp_ln255_fu_145_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op86_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((ap_predicate_op82_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY_int_regslice;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (ap_predicate_op82_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out0_V_TVALID_int_regslice = 1'b1;
    end else begin
        out0_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (icmp_ln255_reg_639_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln292_1_fu_296_p2 = (add_ln292_fu_290_p2 + ap_sig_allocacmp_p_load);

assign add_ln292_fu_290_p2 = ($signed(and_ln_fu_282_p3) + $signed(3'd7));

assign and_ln_fu_282_p3 = {{ret_fu_274_p3}, {2'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln255_fu_145_p2 == 1'd0)));
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op82_write_state2 == 1'b1) & (out0_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op82_write_state2 == 1'b1) & (out0_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op86_write_state3 == 1'b1) & (out0_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out0_V_U_apdone_blk == 1'b1) | ((ap_predicate_op86_write_state3 == 1'b1) & (out0_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_106 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_133 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op82_write_state2 = ((ret_reg_715 == 1'd1) & (icmp_ln255_reg_639 == 1'd0));
end

always @ (*) begin
    ap_predicate_op86_write_state3 = ((ret_reg_715_pp0_iter1_reg == 1'd1) & (icmp_ln255_reg_639_pp0_iter1_reg == 1'd0));
end

assign i_2_fu_151_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign icmp_ln224_10_fu_539_p2 = ((trunc_ln224_s_fu_529_p4 < trunc_ln258_1_reg_703) ? 1'b1 : 1'b0);

assign icmp_ln224_11_fu_561_p2 = ((trunc_ln224_10_fu_551_p4 < trunc_ln258_10_reg_709) ? 1'b1 : 1'b0);

assign icmp_ln224_1_fu_341_p2 = ((trunc_ln224_1_fu_331_p4 < trunc_ln258_2_reg_649) ? 1'b1 : 1'b0);

assign icmp_ln224_2_fu_363_p2 = ((trunc_ln224_2_fu_353_p4 < trunc_ln258_3_reg_655) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_385_p2 = ((trunc_ln224_3_fu_375_p4 < trunc_ln258_4_reg_661) ? 1'b1 : 1'b0);

assign icmp_ln224_4_fu_407_p2 = ((trunc_ln224_4_fu_397_p4 < trunc_ln258_5_reg_667) ? 1'b1 : 1'b0);

assign icmp_ln224_5_fu_429_p2 = ((trunc_ln224_5_fu_419_p4 < trunc_ln258_6_reg_673) ? 1'b1 : 1'b0);

assign icmp_ln224_6_fu_451_p2 = ((trunc_ln224_6_fu_441_p4 < trunc_ln258_7_reg_679) ? 1'b1 : 1'b0);

assign icmp_ln224_7_fu_473_p2 = ((trunc_ln224_7_fu_463_p4 < trunc_ln258_8_reg_685) ? 1'b1 : 1'b0);

assign icmp_ln224_8_fu_495_p2 = ((trunc_ln224_8_fu_485_p4 < trunc_ln258_9_reg_691) ? 1'b1 : 1'b0);

assign icmp_ln224_9_fu_517_p2 = ((trunc_ln224_9_fu_507_p4 < trunc_ln258_s_reg_697) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_319_p2 = ((trunc_ln224_fu_315_p1 < trunc_ln258_reg_643) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_145_p2 = ((ap_sig_allocacmp_i_1 == 8'd144) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign or_ln127_s_fu_573_p13 = {{{{{{{{{{{{select_ln127_11_fu_566_p3}, {select_ln127_10_fu_544_p3}}, {select_ln127_9_fu_522_p3}}, {select_ln127_8_fu_500_p3}}, {select_ln127_7_fu_478_p3}}, {select_ln127_6_fu_456_p3}}, {select_ln127_5_fu_434_p3}}, {select_ln127_4_fu_412_p3}}, {select_ln127_3_fu_390_p3}}, {select_ln127_2_fu_368_p3}}, {select_ln127_1_fu_346_p3}}, {select_ln127_fu_324_p3}};

assign out0_V_TDATA_int_regslice = or_ln127_s_fu_573_p13;

assign out0_V_TVALID = regslice_both_out0_V_U_vld_out;

assign ret_fu_274_p3 = ap_sig_allocacmp_p_load[32'd2];

assign select_ln127_10_fu_544_p3 = ((icmp_ln224_10_fu_539_p2[0:0] == 1'b1) ? trunc_ln258_1_reg_703 : trunc_ln224_s_fu_529_p4);

assign select_ln127_11_fu_566_p3 = ((icmp_ln224_11_fu_561_p2[0:0] == 1'b1) ? trunc_ln258_10_reg_709 : trunc_ln224_10_fu_551_p4);

assign select_ln127_1_fu_346_p3 = ((icmp_ln224_1_fu_341_p2[0:0] == 1'b1) ? trunc_ln258_2_reg_649 : trunc_ln224_1_fu_331_p4);

assign select_ln127_2_fu_368_p3 = ((icmp_ln224_2_fu_363_p2[0:0] == 1'b1) ? trunc_ln258_3_reg_655 : trunc_ln224_2_fu_353_p4);

assign select_ln127_3_fu_390_p3 = ((icmp_ln224_3_fu_385_p2[0:0] == 1'b1) ? trunc_ln258_4_reg_661 : trunc_ln224_3_fu_375_p4);

assign select_ln127_4_fu_412_p3 = ((icmp_ln224_4_fu_407_p2[0:0] == 1'b1) ? trunc_ln258_5_reg_667 : trunc_ln224_4_fu_397_p4);

assign select_ln127_5_fu_434_p3 = ((icmp_ln224_5_fu_429_p2[0:0] == 1'b1) ? trunc_ln258_6_reg_673 : trunc_ln224_5_fu_419_p4);

assign select_ln127_6_fu_456_p3 = ((icmp_ln224_6_fu_451_p2[0:0] == 1'b1) ? trunc_ln258_7_reg_679 : trunc_ln224_6_fu_441_p4);

assign select_ln127_7_fu_478_p3 = ((icmp_ln224_7_fu_473_p2[0:0] == 1'b1) ? trunc_ln258_8_reg_685 : trunc_ln224_7_fu_463_p4);

assign select_ln127_8_fu_500_p3 = ((icmp_ln224_8_fu_495_p2[0:0] == 1'b1) ? trunc_ln258_9_reg_691 : trunc_ln224_8_fu_485_p4);

assign select_ln127_9_fu_522_p3 = ((icmp_ln224_9_fu_517_p2[0:0] == 1'b1) ? trunc_ln258_s_reg_697 : trunc_ln224_9_fu_507_p4);

assign select_ln127_fu_324_p3 = ((icmp_ln224_fu_319_p2[0:0] == 1'b1) ? trunc_ln258_reg_643 : trunc_ln224_fu_315_p1);

assign select_ln255_fu_606_p3 = ((ret_reg_715[0:0] == 1'b1) ? 36'd0 : or_ln127_s_fu_573_p13);

assign trunc_ln224_10_fu_551_p4 = {{ap_sig_allocacmp_phi_ln257_load[35:33]}};

assign trunc_ln224_1_fu_331_p4 = {{ap_sig_allocacmp_phi_ln257_load[5:3]}};

assign trunc_ln224_2_fu_353_p4 = {{ap_sig_allocacmp_phi_ln257_load[8:6]}};

assign trunc_ln224_3_fu_375_p4 = {{ap_sig_allocacmp_phi_ln257_load[11:9]}};

assign trunc_ln224_4_fu_397_p4 = {{ap_sig_allocacmp_phi_ln257_load[14:12]}};

assign trunc_ln224_5_fu_419_p4 = {{ap_sig_allocacmp_phi_ln257_load[17:15]}};

assign trunc_ln224_6_fu_441_p4 = {{ap_sig_allocacmp_phi_ln257_load[20:18]}};

assign trunc_ln224_7_fu_463_p4 = {{ap_sig_allocacmp_phi_ln257_load[23:21]}};

assign trunc_ln224_8_fu_485_p4 = {{ap_sig_allocacmp_phi_ln257_load[26:24]}};

assign trunc_ln224_9_fu_507_p4 = {{ap_sig_allocacmp_phi_ln257_load[29:27]}};

assign trunc_ln224_fu_315_p1 = ap_sig_allocacmp_phi_ln257_load[2:0];

assign trunc_ln224_s_fu_529_p4 = {{ap_sig_allocacmp_phi_ln257_load[32:30]}};

assign trunc_ln258_fu_160_p1 = in0_V_TDATA_int_regslice[2:0];

endmodule //Pool_hls_0_Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_s
