// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Pool_hls_0_Pool_hls_0,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.935500,HLS_SYN_LAT=147,HLS_SYN_TPT=148,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=96,HLS_SYN_LUT=376,HLS_VERSION=2023_2}" *)

module Pool_hls_0 (
        in0_V_TDATA,
        out0_V_TDATA,
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        in0_V_TREADY,
        out0_V_TVALID,
        out0_V_TREADY
);


input  [39:0] in0_V_TDATA;
output  [39:0] out0_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
output   in0_V_TREADY;
output   out0_V_TVALID;
input   out0_V_TREADY;

 reg    ap_rst_n_inv;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_start;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_done;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_continue;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_idle;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_ready;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_in0_V_TREADY;
wire   [39:0] Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TDATA;
wire    Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TVALID;

Pool_hls_0_Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_s Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_start),
    .ap_done(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_done),
    .ap_continue(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_continue),
    .ap_idle(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_idle),
    .ap_ready(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_ready),
    .in0_V_TVALID(in0_V_TVALID),
    .out0_V_TREADY(out0_V_TREADY),
    .in0_V_TDATA(in0_V_TDATA),
    .in0_V_TREADY(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_in0_V_TREADY),
    .out0_V_TDATA(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TDATA),
    .out0_V_TVALID(Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TVALID)
);

assign Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_continue = 1'b1;

assign Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_ap_start = 1'b1;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign in0_V_TREADY = Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_in0_V_TREADY;

assign out0_V_TDATA = Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TDATA;

assign out0_V_TVALID = Pool_batch_144ul_4ul_vector_vector_MaxPoolFunction_vector_ap_uint_12ul_U0_out0_V_TVALID;

endmodule //Pool_hls_0
